### ISSUE TITLE
Tested on 3478a works ok but

### ISSUE THREAD

**Issue by subzero2379** [xyphro/HP3457-OLED-display#9]
Tested on 3478a works ok but ehen press az on off shows 4 w ir 2 w measurements ok but function needs. Some gux
![IMG_20240308_163403](https://github.com/xyphro/HP3457-OLED-display/assets/75571376/57f8154d-86cd-4d3e-9db8-07f371aa0a6f)

**Comment by subzero2379** [comment]
Need to replace smpl with srq
2 w with  azoff
Azoff with 4w 
And remove math icon

**Comment by subzero2379** [comment]
And have to kove the dot to third oled i think

**Comment by subzero2379** [comment]
Flashed icons 3478a hex but i dont have the right icons i have smpl instead of srq
2winstead of azoff  azoff instead of 4 w

**Comment by subzero2379** [comment]
Compare 3457 icons and 3478 icons and are the same on hex compare,most probably the wame file twice,tried to complile on avr studio but i dont have idea how to do it please help

**Comment by subzero2379** [comment]
Ok fixed i compuled the fw and all good
![IMG_20240316_130232](https://github.com/xyphro/HP3457-OLED-display/assets/75571376/5346aabb-98df-4729-8505-040b2bfd46e9)
![Uploading IMG_20240316_130236.jpg…]()

**Comment by titanium67-cell** [comment]
Which firmware did you use? Same problem, not many icons appear even during the self-test. The same device is HP3478A. THANKS

**Comment by subzero2379** [comment]
download fixed fw from eevblog thread i upload compiled firmware there

**Comment by xyphro** [comment]
Can you share the link? Would make sense to include it here.

**Comment by titanium67-cell** [comment]
Condividi link e versione Grazie

**Comment by subzero2379** [comment]
https://www.eevblog.com/forum/testgear/hp3548-hp3457-oled-display/75/

**Comment by xyphro** [comment]
And what change was applied? Would be great to contribute it back to avoid others running into that issue.
Only see a binary there.

**Comment by titanium67-cell** [comment]
<img width="1080" height="998" alt="Image" src="https://github.com/user-attachments/assets/60fa37a7-6195-45d4-9a54-213d794538ae" />

Is this it? I've already installed it and haven't noticed any improvements. Can you post a photo or two of the icons you see? Thanks.
